package dev.bilby.ui.theme

import androidx.annotation.StringRes
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import dev.bilby.R

/**
 * 内置配色。**种子取自日本传统色**(NipponColors,色值出自《日本の伝統色》PIE BOOKS 2007,
 * 经 nipponcolors.com 的 `php/io.php?color=<ROMAJI>` 接口逐个取得),界面上中文用和名汉字,
 * 英文用罗马音。第一项是应用本来的蓝紫,也就是品牌色(图标底色、启动窗口),种子来历见
 * Color.kt;它不是传统色,名字就叫 Bilby,不硬套一个相近的和名。
 *
 * 选这八个:色相绕色环一圈拉开(红、橙、黄、黄绿、绿、青、紫、品红),和品牌色的蓝紫也不
 * 挨着 —— tonal spot 只保留种子的色相、把彩度压到一个固定档,两个色相相近的种子算出来几乎是
 * 同一套。加上「系统」和 Bilby 一共十格,设置页排成 5×2。
 *
 * 每一套都是**离线算好的常量**,和 Color.kt 同一个做法、同一组参数:material-color-utilities
 * 0.3.0(npm)的 `SchemeTonalSpot`,对比度 0,即 2021 版规范。用这组参数重算默认种子,
 * 得到的表和 Color.kt 里那套逐项一致。不在运行时算:那要多一个依赖,而且得确保它实现的
 * 规范版本和系统的 `dynamicColorScheme` 一致,否则同一台机器上内置色和壁纸取色的观感对不上。
 * 加一个种子就再跑一次生成器,把两套表贴进来。
 */
enum class ThemePalette(
    /** 种子色本身,设置页的色板上画这个。 */
    val seed: Color,
    @StringRes val label: Int,
) {
    // 和名按色相绕一圈排:红、橙、黄、黄绿、绿、青、紫、品红。
    Default(Color(0xFF4A5C92), R.string.theme_palette_default),
    Kurenai(Color(0xFFCB1B45), R.string.theme_palette_kurenai),
    Kanzo(Color(0xFFFC9F4D), R.string.theme_palette_kanzo),
    Yamabuki(Color(0xFFFFB11B), R.string.theme_palette_yamabuki),
    Moegi(Color(0xFF7BA23F), R.string.theme_palette_moegi),
    Wakatake(Color(0xFF5DAC81), R.string.theme_palette_wakatake),
    Asagi(Color(0xFF33A6B8), R.string.theme_palette_asagi),
    Kikyo(Color(0xFF6A4C9C), R.string.theme_palette_kikyo),
    Botan(Color(0xFFC1328E), R.string.theme_palette_botan),
    ;

    internal val schemes: PaletteSchemes
        get() = when (this) {
            Default -> PaletteSchemes(BilbyLightColors, BilbyDarkColors)
            Kurenai -> KurenaiSchemes
            Kanzo -> KanzoSchemes
            Yamabuki -> YamabukiSchemes
            Moegi -> MoegiSchemes
            Wakatake -> WakatakeSchemes
            Asagi -> AsagiSchemes
            Kikyo -> KikyoSchemes
            Botan -> BotanSchemes
        }
}

internal class PaletteSchemes(val light: ColorScheme, val dark: ColorScheme)

// 紅 KURENAI #CB1B45
private val KurenaiSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF8F4A50),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDADB),
        onPrimaryContainer = Color(0xFF72333A),
        inversePrimary = Color(0xFFFFB2B7),
        secondary = Color(0xFF765658),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDADB),
        onSecondaryContainer = Color(0xFF5C3F41),
        tertiary = Color(0xFF775930),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDDB4),
        onTertiaryContainer = Color(0xFF5D421B),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF22191A),
        surfaceVariant = Color(0xFFF4DDDE),
        onSurfaceVariant = Color(0xFF524344),
        surfaceTint = Color(0xFF8F4A50),
        inverseSurface = Color(0xFF382E2E),
        inverseOnSurface = Color(0xFFFFEDED),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF857373),
        outlineVariant = Color(0xFFD7C1C2),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceDim = Color(0xFFE7D6D6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F0),
        surfaceContainer = Color(0xFFFCEAEA),
        surfaceContainerHigh = Color(0xFFF6E4E4),
        surfaceContainerHighest = Color(0xFFF0DEDE),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFFB2B7),
        onPrimary = Color(0xFF561D24),
        primaryContainer = Color(0xFF72333A),
        onPrimaryContainer = Color(0xFFFFDADB),
        inversePrimary = Color(0xFF8F4A50),
        secondary = Color(0xFFE6BDBE),
        onSecondary = Color(0xFF44292B),
        secondaryContainer = Color(0xFF5C3F41),
        onSecondaryContainer = Color(0xFFFFDADB),
        tertiary = Color(0xFFE7C08E),
        onTertiary = Color(0xFF432C06),
        tertiaryContainer = Color(0xFF5D421B),
        onTertiaryContainer = Color(0xFFFFDDB4),
        background = Color(0xFF1A1112),
        onBackground = Color(0xFFF0DEDE),
        surface = Color(0xFF1A1112),
        onSurface = Color(0xFFF0DEDE),
        surfaceVariant = Color(0xFF524344),
        onSurfaceVariant = Color(0xFFD7C1C2),
        surfaceTint = Color(0xFFFFB2B7),
        inverseSurface = Color(0xFFF0DEDE),
        inverseOnSurface = Color(0xFF382E2E),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF9F8C8D),
        outlineVariant = Color(0xFF524344),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF413737),
        surfaceDim = Color(0xFF1A1112),
        surfaceContainerLowest = Color(0xFF140C0D),
        surfaceContainerLow = Color(0xFF22191A),
        surfaceContainer = Color(0xFF271D1E),
        surfaceContainerHigh = Color(0xFF312828),
        surfaceContainerHighest = Color(0xFF3D3233),
    ),
)

// 山吹 YAMABUKI #FFB11B
private val YamabukiSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF7E570F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDDB0),
        onPrimaryContainer = Color(0xFF614000),
        inversePrimary = Color(0xFFF2BE6E),
        secondary = Color(0xFF6F5B40),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFF9DEBB),
        onSecondaryContainer = Color(0xFF55442A),
        tertiary = Color(0xFF506441),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFD2EABD),
        onTertiaryContainer = Color(0xFF394C2B),
        background = Color(0xFFFFF8F3),
        onBackground = Color(0xFF201B13),
        surface = Color(0xFFFFF8F3),
        onSurface = Color(0xFF201B13),
        surfaceVariant = Color(0xFFEFE0CF),
        onSurfaceVariant = Color(0xFF4F4539),
        surfaceTint = Color(0xFF7E570F),
        inverseSurface = Color(0xFF362F27),
        inverseOnSurface = Color(0xFFFBEFE2),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF817567),
        outlineVariant = Color(0xFFD2C4B4),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F3),
        surfaceDim = Color(0xFFE4D8CC),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFEF2E5),
        surfaceContainer = Color(0xFFF8ECDF),
        surfaceContainerHigh = Color(0xFFF2E6DA),
        surfaceContainerHighest = Color(0xFFEDE1D4),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFF2BE6E),
        onPrimary = Color(0xFF442C00),
        primaryContainer = Color(0xFF614000),
        onPrimaryContainer = Color(0xFFFFDDB0),
        inversePrimary = Color(0xFF7E570F),
        secondary = Color(0xFFDCC3A1),
        onSecondary = Color(0xFF3D2E16),
        secondaryContainer = Color(0xFF55442A),
        onSecondaryContainer = Color(0xFFF9DEBB),
        tertiary = Color(0xFFB7CEA2),
        onTertiary = Color(0xFF233517),
        tertiaryContainer = Color(0xFF394C2B),
        onTertiaryContainer = Color(0xFFD2EABD),
        background = Color(0xFF18130B),
        onBackground = Color(0xFFEDE1D4),
        surface = Color(0xFF18130B),
        onSurface = Color(0xFFEDE1D4),
        surfaceVariant = Color(0xFF4F4539),
        onSurfaceVariant = Color(0xFFD2C4B4),
        surfaceTint = Color(0xFFF2BE6E),
        inverseSurface = Color(0xFFEDE1D4),
        inverseOnSurface = Color(0xFF362F27),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF9B8F80),
        outlineVariant = Color(0xFF4F4539),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF3F382F),
        surfaceDim = Color(0xFF18130B),
        surfaceContainerLowest = Color(0xFF120D07),
        surfaceContainerLow = Color(0xFF201B13),
        surfaceContainer = Color(0xFF241F17),
        surfaceContainerHigh = Color(0xFF2F2921),
        surfaceContainerHighest = Color(0xFF3A342B),
    ),
)

// 若竹 WAKATAKE #5DAC81
private val WakatakeSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF276A49),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFACF2C8),
        onPrimaryContainer = Color(0xFF045233),
        inversePrimary = Color(0xFF91D5AD),
        secondary = Color(0xFF4E6355),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD0E8D7),
        onSecondaryContainer = Color(0xFF374B3E),
        tertiary = Color(0xFF3C6471),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBFE9F9),
        onTertiaryContainer = Color(0xFF224C59),
        background = Color(0xFFF6FBF4),
        onBackground = Color(0xFF171D19),
        surface = Color(0xFFF6FBF4),
        onSurface = Color(0xFF171D19),
        surfaceVariant = Color(0xFFDCE5DC),
        onSurfaceVariant = Color(0xFF404942),
        surfaceTint = Color(0xFF276A49),
        inverseSurface = Color(0xFF2C322D),
        inverseOnSurface = Color(0xFFEDF2EB),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF707972),
        outlineVariant = Color(0xFFC0C9C0),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF6FBF4),
        surfaceDim = Color(0xFFD6DBD5),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF0F5EE),
        surfaceContainer = Color(0xFFEAEFE9),
        surfaceContainerHigh = Color(0xFFE4EAE3),
        surfaceContainerHighest = Color(0xFFDFE4DD),
    ),
    dark = darkColorScheme(
        primary = Color(0xFF91D5AD),
        onPrimary = Color(0xFF003821),
        primaryContainer = Color(0xFF045233),
        onPrimaryContainer = Color(0xFFACF2C8),
        inversePrimary = Color(0xFF276A49),
        secondary = Color(0xFFB5CCBB),
        onSecondary = Color(0xFF203529),
        secondaryContainer = Color(0xFF374B3E),
        onSecondaryContainer = Color(0xFFD0E8D7),
        tertiary = Color(0xFFA4CDDC),
        onTertiary = Color(0xFF043542),
        tertiaryContainer = Color(0xFF224C59),
        onTertiaryContainer = Color(0xFFBFE9F9),
        background = Color(0xFF0F1511),
        onBackground = Color(0xFFDFE4DD),
        surface = Color(0xFF0F1511),
        onSurface = Color(0xFFDFE4DD),
        surfaceVariant = Color(0xFF404942),
        onSurfaceVariant = Color(0xFFC0C9C0),
        surfaceTint = Color(0xFF91D5AD),
        inverseSurface = Color(0xFFDFE4DD),
        inverseOnSurface = Color(0xFF2C322D),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8A938B),
        outlineVariant = Color(0xFF404942),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF353B36),
        surfaceDim = Color(0xFF0F1511),
        surfaceContainerLowest = Color(0xFF0A0F0C),
        surfaceContainerLow = Color(0xFF171D19),
        surfaceContainer = Color(0xFF1B211D),
        surfaceContainerHigh = Color(0xFF262B27),
        surfaceContainerHighest = Color(0xFF303632),
    ),
)

// 浅葱 ASAGI #33A6B8
private val AsagiSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF006875),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF9EEFFF),
        onPrimaryContainer = Color(0xFF004E59),
        inversePrimary = Color(0xFF82D3E2),
        secondary = Color(0xFF4A6267),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCDE7ED),
        onSecondaryContainer = Color(0xFF334B4F),
        tertiary = Color(0xFF535D7E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFDBE1FF),
        onTertiaryContainer = Color(0xFF3C4665),
        background = Color(0xFFF5FAFC),
        onBackground = Color(0xFF171D1E),
        surface = Color(0xFFF5FAFC),
        onSurface = Color(0xFF171D1E),
        surfaceVariant = Color(0xFFDBE4E6),
        onSurfaceVariant = Color(0xFF3F484A),
        surfaceTint = Color(0xFF006875),
        inverseSurface = Color(0xFF2B3133),
        inverseOnSurface = Color(0xFFECF2F3),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF6F797B),
        outlineVariant = Color(0xFFBFC8CA),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF5FAFC),
        surfaceDim = Color(0xFFD5DBDC),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEFF5F6),
        surfaceContainer = Color(0xFFE9EFF0),
        surfaceContainerHigh = Color(0xFFE3E9EA),
        surfaceContainerHighest = Color(0xFFDEE3E5),
    ),
    dark = darkColorScheme(
        primary = Color(0xFF82D3E2),
        onPrimary = Color(0xFF00363E),
        primaryContainer = Color(0xFF004E59),
        onPrimaryContainer = Color(0xFF9EEFFF),
        inversePrimary = Color(0xFF006875),
        secondary = Color(0xFFB1CBD1),
        onSecondary = Color(0xFF1C3438),
        secondaryContainer = Color(0xFF334B4F),
        onSecondaryContainer = Color(0xFFCDE7ED),
        tertiary = Color(0xFFBBC5EA),
        onTertiary = Color(0xFF252F4D),
        tertiaryContainer = Color(0xFF3C4665),
        onTertiaryContainer = Color(0xFFDBE1FF),
        background = Color(0xFF0E1416),
        onBackground = Color(0xFFDEE3E5),
        surface = Color(0xFF0E1416),
        onSurface = Color(0xFFDEE3E5),
        surfaceVariant = Color(0xFF3F484A),
        onSurfaceVariant = Color(0xFFBFC8CA),
        surfaceTint = Color(0xFF82D3E2),
        inverseSurface = Color(0xFFDEE3E5),
        inverseOnSurface = Color(0xFF2B3133),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF899294),
        outlineVariant = Color(0xFF3F484A),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF343A3C),
        surfaceDim = Color(0xFF0E1416),
        surfaceContainerLowest = Color(0xFF090F10),
        surfaceContainerLow = Color(0xFF171D1E),
        surfaceContainer = Color(0xFF1B2122),
        surfaceContainerHigh = Color(0xFF252B2C),
        surfaceContainerHighest = Color(0xFF303637),
    ),
)

// 桔梗 KIKYO #6A4C9C
private val KikyoSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF69548D),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFECDCFF),
        onPrimaryContainer = Color(0xFF513C73),
        inversePrimary = Color(0xFFD4BBFC),
        secondary = Color(0xFF635B70),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEADEF7),
        onSecondaryContainer = Color(0xFF4B4357),
        tertiary = Color(0xFF7F525C),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD9E0),
        onTertiaryContainer = Color(0xFF643B45),
        background = Color(0xFFFEF7FF),
        onBackground = Color(0xFF1D1A20),
        surface = Color(0xFFFEF7FF),
        onSurface = Color(0xFF1D1A20),
        surfaceVariant = Color(0xFFE8E0EB),
        onSurfaceVariant = Color(0xFF49454E),
        surfaceTint = Color(0xFF69548D),
        inverseSurface = Color(0xFF322F35),
        inverseOnSurface = Color(0xFFF5EEF7),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF7A757F),
        outlineVariant = Color(0xFFCBC4CF),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFEF7FF),
        surfaceDim = Color(0xFFDED8E0),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF8F1F9),
        surfaceContainer = Color(0xFFF3ECF4),
        surfaceContainerHigh = Color(0xFFEDE6EE),
        surfaceContainerHighest = Color(0xFFE7E0E8),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFD4BBFC),
        onPrimary = Color(0xFF3A255B),
        primaryContainer = Color(0xFF513C73),
        onPrimaryContainer = Color(0xFFECDCFF),
        inversePrimary = Color(0xFF69548D),
        secondary = Color(0xFFCEC2DB),
        onSecondary = Color(0xFF342D40),
        secondaryContainer = Color(0xFF4B4357),
        onSecondaryContainer = Color(0xFFEADEF7),
        tertiary = Color(0xFFF1B7C3),
        onTertiary = Color(0xFF4A252F),
        tertiaryContainer = Color(0xFF643B45),
        onTertiaryContainer = Color(0xFFFFD9E0),
        background = Color(0xFF151218),
        onBackground = Color(0xFFE7E0E8),
        surface = Color(0xFF151218),
        onSurface = Color(0xFFE7E0E8),
        surfaceVariant = Color(0xFF49454E),
        onSurfaceVariant = Color(0xFFCBC4CF),
        surfaceTint = Color(0xFFD4BBFC),
        inverseSurface = Color(0xFFE7E0E8),
        inverseOnSurface = Color(0xFF322F35),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF958E99),
        outlineVariant = Color(0xFF49454E),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF3B383E),
        surfaceDim = Color(0xFF151218),
        surfaceContainerLowest = Color(0xFF0F0D12),
        surfaceContainerLow = Color(0xFF1D1A20),
        surfaceContainer = Color(0xFF211E24),
        surfaceContainerHigh = Color(0xFF2C292F),
        surfaceContainerHighest = Color(0xFF37343A),
    ),
)

// 萱草 KANZO #FC9F4D
private val KanzoSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF88511E),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDCC3),
        onPrimaryContainer = Color(0xFF6C3A07),
        inversePrimary = Color(0xFFFFB77D),
        secondary = Color(0xFF745944),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDCC3),
        onSecondaryContainer = Color(0xFF5A422E),
        tertiary = Color(0xFF5C6236),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE1E7B0),
        onTertiaryContainer = Color(0xFF454A21),
        background = Color(0xFFFFF8F5),
        onBackground = Color(0xFF221A14),
        surface = Color(0xFFFFF8F5),
        onSurface = Color(0xFF221A14),
        surfaceVariant = Color(0xFFF3DFD2),
        onSurfaceVariant = Color(0xFF51443B),
        surfaceTint = Color(0xFF88511E),
        inverseSurface = Color(0xFF382F28),
        inverseOnSurface = Color(0xFFFEEEE4),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF847469),
        outlineVariant = Color(0xFFD6C3B6),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F5),
        surfaceDim = Color(0xFFE7D7CE),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF1E9),
        surfaceContainer = Color(0xFFFBEBE1),
        surfaceContainerHigh = Color(0xFFF5E5DB),
        surfaceContainerHighest = Color(0xFFEFE0D6),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFFB77D),
        onPrimary = Color(0xFF4D2600),
        primaryContainer = Color(0xFF6C3A07),
        onPrimaryContainer = Color(0xFFFFDCC3),
        inversePrimary = Color(0xFF88511E),
        secondary = Color(0xFFE3C0A6),
        onSecondary = Color(0xFF422C1A),
        secondaryContainer = Color(0xFF5A422E),
        onSecondaryContainer = Color(0xFFFFDCC3),
        tertiary = Color(0xFFC5CB96),
        onTertiary = Color(0xFF2E330D),
        tertiaryContainer = Color(0xFF454A21),
        onTertiaryContainer = Color(0xFFE1E7B0),
        background = Color(0xFF19120C),
        onBackground = Color(0xFFEFE0D6),
        surface = Color(0xFF19120C),
        onSurface = Color(0xFFEFE0D6),
        surfaceVariant = Color(0xFF51443B),
        onSurfaceVariant = Color(0xFFD6C3B6),
        surfaceTint = Color(0xFFFFB77D),
        inverseSurface = Color(0xFFEFE0D6),
        inverseOnSurface = Color(0xFF382F28),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF9E8E82),
        outlineVariant = Color(0xFF51443B),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF413731),
        surfaceDim = Color(0xFF19120C),
        surfaceContainerLowest = Color(0xFF140D08),
        surfaceContainerLow = Color(0xFF221A14),
        surfaceContainer = Color(0xFF261E18),
        surfaceContainerHigh = Color(0xFF312822),
        surfaceContainerHighest = Color(0xFF3C332C),
    ),
)

// 萌黄 MOEGI #7BA23F
private val MoegiSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF4E6629),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD0EDA1),
        onPrimaryContainer = Color(0xFF374D13),
        inversePrimary = Color(0xFFB4D087),
        secondary = Color(0xFF586249),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDDE7C7),
        onSecondaryContainer = Color(0xFF414A32),
        tertiary = Color(0xFF396662),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBCECE6),
        onTertiaryContainer = Color(0xFF1F4E4A),
        background = Color(0xFFFAFAEE),
        onBackground = Color(0xFF1A1C16),
        surface = Color(0xFFFAFAEE),
        onSurface = Color(0xFF1A1C16),
        surfaceVariant = Color(0xFFE1E4D5),
        onSurfaceVariant = Color(0xFF45483D),
        surfaceTint = Color(0xFF4E6629),
        inverseSurface = Color(0xFF2F312A),
        inverseOnSurface = Color(0xFFF1F2E6),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF75786C),
        outlineVariant = Color(0xFFC5C8B9),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFAFAEE),
        surfaceDim = Color(0xFFDADBD0),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF4F4E9),
        surfaceContainer = Color(0xFFEEEFE3),
        surfaceContainerHigh = Color(0xFFE8E9DE),
        surfaceContainerHighest = Color(0xFFE2E3D8),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFB4D087),
        onPrimary = Color(0xFF223600),
        primaryContainer = Color(0xFF374D13),
        onPrimaryContainer = Color(0xFFD0EDA1),
        inversePrimary = Color(0xFF4E6629),
        secondary = Color(0xFFC0CAAC),
        onSecondary = Color(0xFF2B331E),
        secondaryContainer = Color(0xFF414A32),
        onSecondaryContainer = Color(0xFFDDE7C7),
        tertiary = Color(0xFFA0D0CA),
        onTertiary = Color(0xFF003734),
        tertiaryContainer = Color(0xFF1F4E4A),
        onTertiaryContainer = Color(0xFFBCECE6),
        background = Color(0xFF12140E),
        onBackground = Color(0xFFE2E3D8),
        surface = Color(0xFF12140E),
        onSurface = Color(0xFFE2E3D8),
        surfaceVariant = Color(0xFF45483D),
        onSurfaceVariant = Color(0xFFC5C8B9),
        surfaceTint = Color(0xFFB4D087),
        inverseSurface = Color(0xFFE2E3D8),
        inverseOnSurface = Color(0xFF2F312A),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8F9285),
        outlineVariant = Color(0xFF45483D),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF383A32),
        surfaceDim = Color(0xFF12140E),
        surfaceContainerLowest = Color(0xFF0D0F09),
        surfaceContainerLow = Color(0xFF1A1C16),
        surfaceContainer = Color(0xFF1E2019),
        surfaceContainerHigh = Color(0xFF292B23),
        surfaceContainerHighest = Color(0xFF33362E),
    ),
)

// 牡丹 BOTAN #C1328E
private val BotanSchemes = PaletteSchemes(
    light = lightColorScheme(
        primary = Color(0xFF874B6C),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD8E9),
        onPrimaryContainer = Color(0xFF6C3453),
        inversePrimary = Color(0xFFFCB0D6),
        secondary = Color(0xFF725763),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFDD9E8),
        onSecondaryContainer = Color(0xFF58404C),
        tertiary = Color(0xFF7F543B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDBC9),
        onTertiaryContainer = Color(0xFF643D26),
        background = Color(0xFFFFF8F8),
        onBackground = Color(0xFF211A1D),
        surface = Color(0xFFFFF8F8),
        onSurface = Color(0xFF211A1D),
        surfaceVariant = Color(0xFFF0DEE4),
        onSurfaceVariant = Color(0xFF504349),
        surfaceTint = Color(0xFF874B6C),
        inverseSurface = Color(0xFF372E32),
        inverseOnSurface = Color(0xFFFCEDF1),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF827379),
        outlineVariant = Color(0xFFD4C2C8),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F8),
        surfaceDim = Color(0xFFE5D6DB),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F4),
        surfaceContainer = Color(0xFFF9EAEF),
        surfaceContainerHigh = Color(0xFFF3E4E9),
        surfaceContainerHighest = Color(0xFFEEDFE3),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFCB0D6),
        onPrimary = Color(0xFF511D3C),
        primaryContainer = Color(0xFF6C3453),
        onPrimaryContainer = Color(0xFFFFD8E9),
        inversePrimary = Color(0xFF874B6C),
        secondary = Color(0xFFDFBDCC),
        onSecondary = Color(0xFF402A35),
        secondaryContainer = Color(0xFF58404C),
        onSecondaryContainer = Color(0xFFFDD9E8),
        tertiary = Color(0xFFF3BA9B),
        onTertiary = Color(0xFF4A2812),
        tertiaryContainer = Color(0xFF643D26),
        onTertiaryContainer = Color(0xFFFFDBC9),
        background = Color(0xFF181115),
        onBackground = Color(0xFFEEDFE3),
        surface = Color(0xFF181115),
        onSurface = Color(0xFFEEDFE3),
        surfaceVariant = Color(0xFF504349),
        onSurfaceVariant = Color(0xFFD4C2C8),
        surfaceTint = Color(0xFFFCB0D6),
        inverseSurface = Color(0xFFEEDFE3),
        inverseOnSurface = Color(0xFF372E32),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF9C8D93),
        outlineVariant = Color(0xFF504349),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF40373A),
        surfaceDim = Color(0xFF181115),
        surfaceContainerLowest = Color(0xFF130C0F),
        surfaceContainerLow = Color(0xFF211A1D),
        surfaceContainer = Color(0xFF251D21),
        surfaceContainerHigh = Color(0xFF30282B),
        surfaceContainerHighest = Color(0xFF3B3236),
    ),
)
